### PR TITLE
Fix lookup of stipple pattern before config is available

### LINKED ISSUE #1027: Default style for hidden lines is inconsistent with the "stipple occluded lines" icon
### System information

- **SolveSpace version:** 3.0~0e0b0252
- **Operating system:** Windows 10

### Expected behavior

Toggling the hidden lines icon to "Stipple occluded lines" should stipple hidden lines by default, as the icon shows.

### Actual behavior

The default style for hidden lines is a solid line.

image

### PR DESCRIPTION
**Pull request by robnee**
Fix a bug with the lookup of stipple pattern for default styles when the config settings are not yet available (install/upgrade/first run). This caused hidden lines to display as continuous rather than dashed.

This fixes #1027

### CODE REVIEW

File: src/style.cpp [hunk 1]
```diff
@@ -412,7 +417,6 @@ std::string Style::StipplePatternName(hStyle hs) {
     return "CONTINUOUS";
```
Comment (ruevs) [inline src/style.cpp:417]:
```suggestion
    return "Continuous";
```

**Review by ruevs — APPROVED** [review]
This looks perfectly logical and does the right thing.
I tested it by deleting `HKEY_CURRENT_USER\Software\SolveSpace\Style_HiddenEdge_StippleType` on Windows and tracing through `style.cpp`line 117.

**Comment by ruevs** [comment]
@phkahler I merged this - it is obovious enough - I hope you do not mind.

**Comment by ruevs** [comment]
Squashed the two commits together and force-pushed master to  709dc31f7865573cbf23c09dbd1946b017e7dc80.

**Comment by phkahler** [comment]
@ruevs  Thank you. I've been preoccupied lately and haven't had much solvespace time so I really appreciate it.
